### ISSUE TITLE
volumes are not working

### ISSUE THREAD

**Issue by ntrvic** [alexec/docker-maven-plugin#60]
conf.yml contains(tried many combinations):
```
packaging:
  add:
    - workfusion-web/target/mturk-web.war
    - workfusion-model/migrations
    - path: conf.yml
ports:
  - 8080

links:
  - mysql:workfusion-web_mysql
  - postgresql:workfusion-web_postgresql

volumes:
  - workfusion-web/target/:/usr/src/app/

tag: workfusion/tomcat_wf_cv
```

when running docker:start,stop,etc... I get the following error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.528 s
[INFO] Finished at: 2015-05-20T16:00:14-04:00
[INFO] Final Memory: 50M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:stop (default-cli) on project workfusion-application: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
[ERROR] at [Source: com.alexecollins.docker.orchestration.util.TokenReplacingReader@2918431c; line: 21, column: 2] (through reference chain: com.alexecollins.docker.orchestration.model.Conf["volumes"])

tried with 2.8.4 & 2.8.6-SNAPSHOT

Am I doing something wrong?

Thanks,

Victor
